baseURL = "https://somanymachines.com/"
languageCode = "en-us"
title = "so many machines"
disableKinds = ["taxonomy", "taxonomyTerm", "section"]
disableHugoGeneratorInject = true

[blackfriday]
   hrefTargetBlank = true
